insert into public.profiles (id, telegram_id, username, first_name, last_name, language)
values
  ('11111111-1111-1111-1111-111111111111', '900000001', 'tossa_seller', 'Tossa', 'Seller', 'am'),
  ('22222222-2222-2222-2222-222222222222', '900000002', 'dessie_jobs', 'Dessie', 'Jobs', 'am')
on conflict (telegram_id) do update set
  username = excluded.username,
  first_name = excluded.first_name,
  last_name = excluded.last_name,
  language = excluded.language,
  updated_at = now();

insert into public.listings (
  id,
  owner_id,
  type,
  title,
  description,
  price,
  salary,
  category,
  location,
  condition,
  job_type,
  phone,
  telegram_username,
  status,
  is_boosted,
  boosted_until,
  expires_at,
  created_at
)
values
  (
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1',
    '11111111-1111-1111-1111-111111111111',
    'item',
    'Samsung A24 clean phone',
    'Clean Samsung phone with charger. Available around Dessie Piassa.',
    14500,
    null,
    'phones',
    'Dessie Piassa',
    'used',
    null,
    '0912345678',
    'tossa_seller',
    'active',
    true,
    now() + interval '2 days',
    now() + interval '6 days',
    now() - interval '2 hours'
  ),
  (
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2',
    '11111111-1111-1111-1111-111111111111',
    'item',
    'New electric mitad',
    'New electric mitad, never used. Good for home or small cafe.',
    3200,
    null,
    'home',
    'Dessie Arada',
    'new',
    null,
    '0912345678',
    'tossa_seller',
    'active',
    false,
    null,
    now() + interval '7 days',
    now() - interval '1 day'
  ),
  (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1',
    '22222222-2222-2222-2222-222222222222',
    'job',
    'Cafe cashier wanted',
    'Full-time cashier needed. Basic reading, friendly service, and punctuality required.',
    null,
    6500,
    'hospitality',
    'Dessie Buanbu Wuha',
    null,
    'Full time',
    '0912456789',
    'dessie_jobs',
    'active',
    false,
    null,
    now() + interval '5 days',
    now() - interval '3 hours'
  ),
  (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2',
    '22222222-2222-2222-2222-222222222222',
    'job',
    'Delivery driver',
    'Driver needed for local delivery work in Dessie. Motorcycle experience preferred.',
    null,
    9000,
    'driver',
    'Dessie Menafesha',
    null,
    'Part time',
    '0912456789',
    'dessie_jobs',
    'active',
    true,
    now() + interval '1 day',
    now() + interval '4 days',
    now() - interval '5 hours'
  )
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  price = excluded.price,
  salary = excluded.salary,
  category = excluded.category,
  location = excluded.location,
  condition = excluded.condition,
  job_type = excluded.job_type,
  phone = excluded.phone,
  telegram_username = excluded.telegram_username,
  status = excluded.status,
  is_boosted = excluded.is_boosted,
  boosted_until = excluded.boosted_until,
  expires_at = excluded.expires_at,
  updated_at = now();
